# Generated by Django 4.2.7 on 2023-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrack', '0003_expense_other_expense_other_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
